source 'https://github.com/CocoaPods/Specs.git'

target 'Linky', :exclusive => true do
  pod "Linky", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Linky", :path => "../"
  pod 'KIF'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCHamcrest'
  pod 'OCMock'
  pod 'PivotalCoreKit/UIKit/SpecHelper/Extensions'
end
